/**
 * Sprint 4.6D – Generisches Standardregelset der Action Engine.
 * Bewusst neutral formuliert: keine Paragraphen, keine schulrechtliche
 * Einzelfalllösung, keine verbindliche Zuständigkeitszuweisung.
 */
import type { ActionCondition, ActionRule } from "./types";

const ANY_EVALUABLE = ["completed", "incomplete", "conflicted", "inProgress"] as const;

function trafficLight(value: string): ActionCondition {
  return {
    source: "assessment",
    field: "trafficLight",
    operator: "trafficLightIs",
    value,
    valueType: "string",
  };
}

function situationTrue(field: string): ActionCondition {
  return { source: "situation", field, operator: "isTrue", valueType: "knowledgeState" };
}

function situationCountGreaterThan(field: string, value: number): ActionCondition {
  return { source: "situation", field, operator: "countGreaterThan", value, valueType: "number" };
}

export const STANDARD_ACTION_RULES: ActionRule[] = [
  {
    id: "action.acute_danger",
    version: 1,
    title: "Akute Gefahr gemeldet",
    description:
      "Es wurde ausdrücklich angegeben, dass eine akute Gefahr besteht, und die Bewertung ist rot.",
    category: "safety",
    enabled: true,
    priority: "critical",
    conditions: [trafficLight("red"), situationTrue("dangerInformation.acuteDangerReported")],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: ["dangerInformation.acuteDangerReported"],
    stopProcessing: false,
    actions: [
      {
        actionKey: "check_immediate_safety",
        title: "Unmittelbare Sicherheit der betroffenen Personen prüfen",
        description:
          "Prüfen Sie, ob die betroffenen Personen aktuell in Sicherheit sind und ob weitere Personen betroffen sein könnten.",
        group: "now",
        priority: "critical",
        required: true,
        responsibleRole: "teacher",
        alternativeResponsibleRoles: ["schoolLeadership"],
        estimatedEffort: "low",
        documentationRequired: true,
        confirmationRequired: true,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "situationFact",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil eine akute Gefahr angegeben wurde.",
        sourceFields: ["dangerInformation.acuteDangerReported"],
      },
      {
        actionKey: "record_emergency_measures",
        title: "Bereits eingeleitete Notfallmaßnahmen erfassen",
        description:
          "Halten Sie fest, welche Sofortmaßnahmen bereits eingeleitet wurden und wer beteiligt war.",
        group: "now",
        priority: "high",
        required: true,
        responsibleRole: "teacher",
        alternativeResponsibleRoles: ["secretariat"],
        dependsOn: ["check_immediate_safety"],
        estimatedEffort: "low",
        documentationRequired: true,
        confirmationRequired: false,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "situationFact",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil bei akuter Gefahr der bisherige Stand nachvollziehbar sein muss.",
        sourceFields: ["dangerInformation.acuteDangerReported", "measuresTaken"],
      },
      {
        actionKey: "involve_leadership_or_emergency",
        title: "Zuständige schulische Leitung oder Notfallstelle einbeziehen",
        description:
          "Prüfen Sie, welche schulische Leitung oder externe Stelle nach den Vorgaben Ihrer Schule einzubeziehen ist.",
        group: "now",
        priority: "critical",
        required: true,
        responsibleRole: "schoolLeadership",
        alternativeResponsibleRoles: ["emergencyServices", "externalAuthority"],
        estimatedEffort: "low",
        documentationRequired: true,
        confirmationRequired: true,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "assessmentTrafficLight",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil die Bewertung kritische Merkmale erfasst hat.",
        sourceFields: ["dangerInformation.acuteDangerReported", "dangerInformation.emergencyServicesInvolved"],
      },
    ],
  },
  {
    id: "action.situation_ongoing",
    version: 1,
    title: "Situation dauert an",
    description: "Es wurde angegeben, dass die Situation aktuell weiterhin andauert.",
    category: "clarification",
    enabled: true,
    priority: "high",
    conditions: [situationTrue("incident.isOngoing")],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: ["incident.isOngoing"],
    stopProcessing: false,
    actions: [
      {
        actionKey: "clarify_ongoing_status",
        title: "Fortdauer der Situation klären und aktuellen Stand dokumentieren",
        description:
          "Klären Sie, ob die Situation weiterhin andauert, und halten Sie den aktuellen Stand strukturiert fest.",
        group: "now",
        priority: "high",
        required: true,
        responsibleRole: "teacher",
        alternativeResponsibleRoles: ["classTeacher"],
        estimatedEffort: "medium",
        documentationRequired: true,
        confirmationRequired: false,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "situationFact",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil angegeben wurde, dass die Situation weiterhin andauert.",
        sourceFields: ["incident.isOngoing"],
      },
    ],
  },
  {
    id: "action.assessment_yellow",
    version: 1,
    title: "Bewertung gelb",
    description: "Die Bewertung weist auf weiteren Klärungsbedarf hin.",
    category: "clarification",
    enabled: true,
    priority: "high",
    conditions: [trafficLight("yellow")],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: [],
    stopProcessing: false,
    actions: [
      {
        actionKey: "complete_open_information",
        title: "Fehlende oder unklare Angaben vervollständigen",
        description:
          "Ergänzen Sie die in der Bewertung genannten offenen Angaben, soweit sie Ihnen bekannt sind.",
        group: "today",
        priority: "high",
        required: true,
        responsibleRole: "teacher",
        estimatedEffort: "medium",
        documentationRequired: false,
        confirmationRequired: false,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "assessmentTrafficLight",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil die Bewertung weiteren Klärungsbedarf ergeben hat.",
        sourceFields: ["completeness.missingRequiredQuestions"],
      },
      {
        actionKey: "document_facts",
        title: "Sachverhalt strukturiert dokumentieren",
        description:
          "Halten Sie den bekannten Ablauf, Beteiligte und Zeitpunkte in Ihrer schulüblichen Form fest.",
        group: "today",
        priority: "normal",
        required: true,
        responsibleRole: "teacher",
        alternativeResponsibleRoles: ["classTeacher"],
        estimatedEffort: "medium",
        documentationRequired: true,
        confirmationRequired: false,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "assessmentTrafficLight",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil die Bewertung eine zeitnahe Bearbeitung nahelegt.",
        sourceFields: ["documentationStatus.notesAvailable"],
      },
      {
        actionKey: "determine_responsible_role",
        title: "Möglicherweise zuständige schulische Rolle festlegen",
        description:
          "Klären Sie schulintern, welche Rolle die weitere Bearbeitung übernimmt.",
        group: "today",
        priority: "normal",
        required: false,
        responsibleRole: "unknown",
        alternativeResponsibleRoles: ["classTeacher", "schoolLeadership", "counsellingTeacher"],
        estimatedEffort: "low",
        documentationRequired: false,
        confirmationRequired: false,
        allowSkip: true,
        allowNotApplicable: true,
        triggerType: "assessmentTrafficLight",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil eine zuständige Rolle für die Weiterbearbeitung noch nicht festgelegt ist.",
        sourceFields: ["responsiblePersonsInformed"],
      },
    ],
  },
  {
    id: "action.assessment_unknown",
    version: 1,
    title: "Bewertung unklar",
    description: "Die Bewertung konnte keine belastbare Einstufung erzeugen.",
    category: "clarification",
    enabled: true,
    priority: "high",
    conditions: [trafficLight("unknown")],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: [],
    stopProcessing: false,
    actions: [
      {
        actionKey: "clarify_missing_information",
        title: "Fehlende entscheidungsrelevante Angaben klären",
        description:
          "Ergänzen Sie die als fehlend ausgewiesenen Angaben oder markieren Sie sie ausdrücklich als unbekannt.",
        group: "now",
        priority: "high",
        required: true,
        responsibleRole: "teacher",
        estimatedEffort: "medium",
        documentationRequired: false,
        confirmationRequired: false,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "assessmentTrafficLight",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil mit den vorhandenen Angaben keine belastbare Einstufung möglich war.",
        sourceFields: ["completeness.missingRequiredQuestions"],
      },
      {
        actionKey: "reevaluate_after_completion",
        title: "Bewertung nach Ergänzung der Angaben erneut ausführen",
        description:
          "Führen Sie die Bewertung erneut aus, sobald die offenen Angaben ergänzt wurden.",
        group: "today",
        priority: "normal",
        required: true,
        responsibleRole: "teacher",
        dependsOn: ["clarify_missing_information"],
        estimatedEffort: "low",
        documentationRequired: false,
        confirmationRequired: false,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "assessmentTrafficLight",
        userFacingReason:
          "Diese Maßnahme wird erst freigegeben, wenn die fehlenden Angaben bearbeitet wurden.",
        sourceFields: [],
      },
    ],
  },
  {
    id: "action.witnesses_present",
    version: 1,
    title: "Zeugen vorhanden",
    description: "Es wurden Zeuginnen oder Zeugen erfasst.",
    category: "documentation",
    enabled: true,
    priority: "normal",
    conditions: [situationCountGreaterThan("witnesses", 0)],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: [],
    stopProcessing: false,
    actions: [
      {
        actionKey: "review_witness_documentation",
        title: "Vorhandene Zeugenaussagen und Dokumentationsstatus prüfen",
        description:
          "Prüfen Sie, ob die erfassten Aussagen vollständig dokumentiert sind. Eine inhaltliche Bewertung erfolgt hier nicht.",
        group: "today",
        priority: "normal",
        required: false,
        responsibleRole: "teacher",
        estimatedEffort: "medium",
        documentationRequired: true,
        confirmationRequired: false,
        allowSkip: true,
        allowNotApplicable: true,
        triggerType: "situationFact",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil mindestens eine Zeugin oder ein Zeuge erfasst wurde.",
        sourceFields: ["witnesses"],
      },
    ],
  },
  {
    id: "action.evidence_present",
    version: 1,
    title: "Nachweise vorhanden",
    description: "Es wurden strukturierte Nachweise erfasst.",
    category: "documentation",
    enabled: true,
    priority: "normal",
    conditions: [situationCountGreaterThan("evidence", 0)],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: [],
    stopProcessing: false,
    actions: [
      {
        actionKey: "secure_evidence_status",
        title: "Vorhandene Nachweise vollständig erfassen und Aufbewahrungsstatus dokumentieren",
        description:
          "Prüfen Sie, ob alle Nachweise erfasst sind und wo sie aufbewahrt werden. Dateien werden hier nicht verändert.",
        group: "today",
        priority: "normal",
        required: false,
        responsibleRole: "teacher",
        alternativeResponsibleRoles: ["dataProtectionOfficer"],
        estimatedEffort: "medium",
        documentationRequired: true,
        confirmationRequired: false,
        allowSkip: true,
        allowNotApplicable: true,
        triggerType: "situationFact",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil mindestens ein Nachweis erfasst wurde.",
        sourceFields: ["evidence"],
      },
    ],
  },
  {
    id: "action.measures_taken",
    version: 1,
    title: "Bereits durchgeführte Maßnahmen",
    description: "Es wurden bereits Maßnahmen erfasst.",
    category: "coordination",
    enabled: true,
    priority: "normal",
    conditions: [situationCountGreaterThan("measuresTaken", 0)],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: [],
    stopProcessing: false,
    actions: [
      {
        actionKey: "review_existing_measures",
        title: "Bereits durchgeführte Maßnahmen und Ergebnisse überprüfen",
        description:
          "Sehen Sie sich die bereits durchgeführten Schritte und deren Ergebnisse an. Eine Bewertung ihrer Richtigkeit erfolgt hier nicht.",
        group: "today",
        priority: "normal",
        required: false,
        responsibleRole: "teacher",
        estimatedEffort: "low",
        documentationRequired: false,
        confirmationRequired: false,
        allowSkip: true,
        allowNotApplicable: true,
        triggerType: "situationFact",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil bereits durchgeführte Schritte erfasst wurden.",
        sourceFields: ["measuresTaken"],
      },
    ],
  },
  {
    id: "action.documentation_missing",
    version: 1,
    title: "Dokumentation fehlt",
    description: "Es liegen keine Notizen oder Gesprächsvermerke vor.",
    category: "documentation",
    enabled: true,
    priority: "normal",
    conditions: [
      {
        source: "situation",
        field: "documentationStatus.notesAvailable",
        operator: "isTrue",
        valueType: "knowledgeState",
        negate: true,
      },
    ],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: ["documentationStatus.notesAvailable"],
    stopProcessing: false,
    actions: [
      {
        actionKey: "add_notes",
        title: "Vorhandene Notizen und Gesprächsvermerke ergänzen",
        description:
          "Ergänzen Sie vorhandene Aufzeichnungen zum Sachverhalt in Ihrer schulüblichen Form.",
        group: "today",
        priority: "normal",
        required: true,
        responsibleRole: "teacher",
        estimatedEffort: "medium",
        documentationRequired: true,
        confirmationRequired: false,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "situationFact",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil bislang keine Notizen oder Gesprächsvermerke erfasst wurden.",
        sourceFields: ["documentationStatus.notesAvailable"],
      },
      {
        actionKey: "check_documentation_completeness",
        title: "Vollständigkeit der Falldokumentation prüfen",
        description:
          "Prüfen Sie zu einem späteren Zeitpunkt, ob die Dokumentation zum Vorgang vollständig ist.",
        group: "later",
        priority: "low",
        required: false,
        responsibleRole: "teacher",
        dependsOn: ["add_notes"],
        estimatedEffort: "low",
        documentationRequired: false,
        confirmationRequired: false,
        allowSkip: true,
        allowNotApplicable: true,
        triggerType: "situationFact",
        userFacingReason:
          "Dieser Schritt ergänzt die Dokumentation, nachdem die Notizen erfasst wurden.",
        sourceFields: ["documentationStatus"],
      },
    ],
  },
  {
    id: "action.assessment_green",
    version: 1,
    title: "Keine unmittelbar kritischen Merkmale",
    description:
      "Die Bewertung hat keine unmittelbar kritischen Merkmale erfasst. Das bedeutet nicht, dass keine Bearbeitung nötig ist.",
    category: "followUp",
    enabled: true,
    priority: "normal",
    conditions: [trafficLight("green")],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: [],
    stopProcessing: false,
    actions: [
      {
        actionKey: "check_case_completeness",
        title: "Sachverhalt auf Vollständigkeit prüfen",
        description:
          "Prüfen Sie, ob alle bekannten Angaben erfasst sind, auch wenn keine kritischen Merkmale vorliegen.",
        group: "today",
        priority: "normal",
        required: true,
        responsibleRole: "teacher",
        estimatedEffort: "low",
        documentationRequired: false,
        confirmationRequired: false,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "assessmentTrafficLight",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil auch ohne kritische Merkmale eine vollständige Erfassung sinnvoll ist.",
        sourceFields: ["completeness.completionPercentage"],
      },
      {
        actionKey: "document_and_reevaluate_later",
        title: "Bearbeitungsstand dokumentieren und bei neuen Erkenntnissen erneut bewerten",
        description:
          "Halten Sie den Bearbeitungsstand fest und bewerten Sie erneut, wenn neue Informationen bekannt werden.",
        group: "later",
        priority: "low",
        required: false,
        responsibleRole: "teacher",
        estimatedEffort: "low",
        documentationRequired: true,
        confirmationRequired: false,
        allowSkip: true,
        allowNotApplicable: true,
        triggerType: "assessmentTrafficLight",
        userFacingReason:
          "Dieser Schritt hält den Bearbeitungsstand für spätere Rückfragen nachvollziehbar.",
        sourceFields: [],
      },
    ],
  },
  {
    id: "action.follow_up",
    version: 1,
    title: "Nachverfolgung",
    description:
      "Mindestens eine verpflichtende Maßnahme wurde bereits abgeschlossen.",
    category: "followUp",
    enabled: true,
    priority: "low",
    conditions: [
      {
        source: "actionContext",
        field: "hasCompletedRequiredAction",
        operator: "isTrue",
        valueType: "boolean",
      },
    ],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: [],
    stopProcessing: false,
    actions: [
      {
        actionKey: "schedule_follow_up",
        title: "Nachverfolgungstermin beziehungsweise erneute Prüfung vormerken",
        description:
          "Merken Sie sich einen Zeitpunkt für eine erneute Prüfung des Vorgangs vor. Eine Kalenderintegration erfolgt nicht.",
        group: "later",
        priority: "low",
        required: false,
        responsibleRole: "teacher",
        alternativeResponsibleRoles: ["classTeacher"],
        estimatedEffort: "low",
        documentationRequired: false,
        confirmationRequired: false,
        allowSkip: true,
        allowNotApplicable: true,
        triggerType: "progress",
        userFacingReason:
          "Dieser Schritt wird vorgeschlagen, weil bereits eine verpflichtende Maßnahme abgeschlossen wurde.",
        sourceFields: [],
      },
    ],
  },
  {
    id: "action.emergency_services_involved",
    version: 1,
    title: "Externe Notfallstellen einbezogen",
    description: "Es wurde angegeben, dass externe Notfallstellen einbezogen wurden.",
    category: "coordination",
    enabled: true,
    priority: "high",
    conditions: [situationTrue("dangerInformation.emergencyServicesInvolved")],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: ["dangerInformation.emergencyServicesInvolved"],
    stopProcessing: false,
    actions: [
      {
        actionKey: "record_external_involvement",
        title: "Einbeziehung externer Stellen dokumentieren",
        description:
          "Halten Sie fest, welche externe Stelle einbezogen wurde und welcher Stand kommuniziert wurde.",
        group: "now",
        priority: "high",
        required: true,
        responsibleRole: "schoolLeadership",
        alternativeResponsibleRoles: ["secretariat"],
        estimatedEffort: "low",
        documentationRequired: true,
        confirmationRequired: false,
        allowSkip: false,
        allowNotApplicable: false,
        triggerType: "situationFact",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil die Einbeziehung externer Notfallstellen angegeben wurde.",
        sourceFields: ["dangerInformation.emergencyServicesInvolved"],
      },
    ],
  },
  {
    id: "action.repeated_incident",
    version: 1,
    title: "Wiederholtes Geschehen",
    description: "Es wurde angegeben, dass sich das Geschehen wiederholt hat.",
    category: "clarification",
    enabled: true,
    priority: "normal",
    conditions: [situationTrue("incident.wasRepeated")],
    requiredAssessmentStatus: [...ANY_EVALUABLE],
    requiredFields: ["incident.wasRepeated"],
    stopProcessing: false,
    actions: [
      {
        actionKey: "review_previous_occurrences",
        title: "Bisherige Vorfälle und deren Bearbeitung zusammenstellen",
        description:
          "Stellen Sie zusammen, welche früheren Vorfälle bekannt sind und wie sie bearbeitet wurden.",
        group: "today",
        priority: "normal",
        required: false,
        responsibleRole: "classTeacher",
        alternativeResponsibleRoles: ["counsellingTeacher"],
        estimatedEffort: "medium",
        documentationRequired: true,
        confirmationRequired: false,
        allowSkip: true,
        allowNotApplicable: true,
        triggerType: "situationFact",
        userFacingReason:
          "Diese Maßnahme wird angezeigt, weil ein wiederholtes Geschehen angegeben wurde.",
        sourceFields: ["incident.wasRepeated"],
      },
    ],
  },
];
