/** Barrel-Export des Grounded Legal Copilot. */
export * from "./types";
export * from "./errors";
export { legalCopilotFlags } from "./featureFlags";
export { copilotTelemetry } from "./telemetry";
export type { CopilotTelemetryEvent, CopilotTelemetryPayload } from "./telemetry";
export { ExplanationModeSpec, EXPLANATION_MODES } from "./ExplanationMode";
export { PROMPT_TEMPLATES_VERSION, SYSTEM_PROMPT, NO_SOURCES_ANSWER, buildUserPrompt } from "./PromptTemplates";
export { PromptBuilder } from "./PromptBuilder";
export type { BuiltPrompt } from "./PromptBuilder";
export { GroundingEngine } from "./GroundingEngine";
export type { GroundingReport, GroundingOptions } from "./GroundingEngine";
export { ContextAssembler } from "./ContextAssembler";
export type { AssembledContext } from "./ContextAssembler";
export { CitationInjector } from "./CitationInjector";
export type { InjectionResult } from "./CitationInjector";
export { HallucinationGuard } from "./HallucinationGuard";
export type { HallucinationReport } from "./HallucinationGuard";
export { ConfidenceCalculator } from "./ConfidenceCalculator";
export { AnswerValidator } from "./AnswerValidator";
export type { AnswerValidationReport } from "./AnswerValidator";
export { AnswerFormatter } from "./AnswerFormatter";
export type { RawLlmAnswer } from "./AnswerFormatter";
export { AnswerGenerator } from "./AnswerGenerator";
export { ConversationMemory } from "./ConversationMemory";
export { ConversationService } from "./ConversationService";
export { InMemoryConversationRepository } from "./ConversationRepository";
export type { ConversationRepositoryPort } from "./ConversationRepository";
export { ConversationMapper } from "./ConversationMapper";
export { CopilotStatisticsBuilder } from "./CopilotStatistics";
export { DisclaimerBuilder } from "./DisclaimerBuilder";
export { SafetyGuard } from "./SafetyGuard";
export type { SafetyDecision } from "./SafetyGuard";
export { FollowUpGenerator } from "./FollowUpGenerator";
export { DocumentTemplateSuggester } from "./DocumentTemplateSuggester";
export type { DocumentTemplateSuggestion, DocumentTemplateId } from "./DocumentTemplateSuggester";
export { TrustIndicatorBuilder } from "./TrustIndicator";
export type { TrustIndicator, TrustSignal, TrustLevel } from "./TrustIndicator";
export { LegalCopilotService } from "./LegalCopilotService";
export type { LegalCopilotDeps } from "./LegalCopilotService";
export { WorkflowRecommender } from "./WorkflowRecommender";
export type { CopilotWorkflowRecommendation } from "./WorkflowRecommender";
