/**
 * Sprint 4.6B – Generisches Standardschema für schulische Situationen.
 * Keine konkreten Praxisfälle, keine rechtliche Bewertung.
 */
import type { SituationSchemaDefinition } from "./types";

export const STANDARD_SITUATION_SCHEMA_ID = "standard-situation-v1";

let questionTitleById: Map<string, string> | null = null;

/**
 * Lesbarer Titel einer Standard-Schema-Frage für teacher-facing Anzeigen
 * (Sprint 4.6J.2-Nachtrag): coverage.missing u. ä. transportieren intern
 * Frage-IDs wie "betroffene.vorhanden" - im Lehrer-Frontend sollen
 * stattdessen die Fragetitel erscheinen. Fallback ist die ID selbst, damit
 * unbekannte oder zukünftige Fragen nie zu leeren Einträgen führen. Die
 * Datenverträge (IDs) bleiben unverändert; nur die Anzeige übersetzt.
 */
export function situationQuestionTitle(questionId: string): string {
  if (!questionTitleById) {
    questionTitleById = new Map(
      buildStandardSituationSchema().questions.map((q) => [q.id, q.title]),
    );
  }
  return questionTitleById.get(questionId) ?? questionId;
}

export function buildStandardSituationSchema(): SituationSchemaDefinition {
  return {
    id: STANDARD_SITUATION_SCHEMA_ID,
    version: 1,
    title: "Situationserfassung",
    description:
      "Strukturierte Erfassung eines schulischen Sachverhalts. Es erfolgt keine Bewertung.",
    sections: [
      { id: "kurzbeschreibung", title: "Kurzbeschreibung", description: "Was ist geschehen? Beschreiben Sie den Sachverhalt in eigenen Worten.", order: 1 },
      { id: "zeit-ort", title: "Zeitpunkt und Ort", description: "Wann und wo hat sich die Situation ereignet?", order: 2 },
      { id: "beteiligte", title: "Beteiligte Personen", description: "Wer war an der Situation beteiligt?", order: 3 },
      { id: "betroffene", title: "Betroffene Personen", description: "Wer ist von der Situation betroffen?", order: 4 },
      { id: "zeugen", title: "Zeugen", description: "Gab es Personen, die die Situation beobachtet haben?", order: 5 },
      { id: "fortdauer", title: "Fortdauer der Situation", description: "Dauert die Situation an oder hat sie sich wiederholt?", order: 6 },
      { id: "gefahren", title: "Angaben zu möglichen Gefahren", description: "Reine Tatsachenangaben. Es erfolgt keine Einschätzung.", order: 7 },
      { id: "nachweise", title: "Vorhandene Nachweise", description: "Welche Unterlagen oder Nachweise liegen vor?", order: 8 },
      { id: "massnahmen", title: "Bereits durchgeführte Maßnahmen", description: "Was wurde bereits unternommen?", order: 9 },
      { id: "informierte", title: "Bereits informierte Stellen oder Personen", description: "Wer wurde bereits informiert?", order: 10 },
      { id: "dokumentation", title: "Vorhandene Dokumentation", description: "Welche Aufzeichnungen existieren bereits?", order: 11 },
      { id: "offene-fragen", title: "Offene Fragen und Unsicherheiten", description: "Was ist derzeit unklar oder nicht bekannt?", order: 12 },
    ],
    questions: [
      {
        id: "kurzbeschreibung.titel",
        section: "kurzbeschreibung",
        title: "Kurztitel des Vorgangs",
        description: "Eine knappe Bezeichnung zur Wiedererkennung.",
        type: "text",
        required: true,
        visible: true,
        order: 1,
        validation: { minLength: 3, maxLength: 120 },
      },
      {
        id: "kurzbeschreibung.text",
        section: "kurzbeschreibung",
        title: "Was ist geschehen?",
        description: "Beschreiben Sie den Sachverhalt sachlich in eigenen Worten.",
        type: "textarea",
        required: true,
        visible: true,
        order: 2,
        validation: { minLength: 10 },
      },
      {
        id: "kurzbeschreibung.kategorie",
        section: "kurzbeschreibung",
        title: "Grobe Einordnung",
        description: "Nur eine Zuordnung zur Sortierung, keine rechtliche Einordnung.",
        type: "singleChoice",
        required: false,
        visible: true,
        order: 3,
        options: [
          { value: "verhalten", label: "Verhalten im Schulalltag" },
          { value: "konflikt", label: "Konflikt zwischen Personen" },
          { value: "kommunikation", label: "Kommunikation und Medien" },
          { value: "organisation", label: "Organisation und Abläufe" },
          { value: "sonstiges", label: "Sonstiges" },
        ],
      },
      {
        id: "zeit-ort.datumBekannt",
        section: "zeit-ort",
        title: "Ist das Datum bekannt?",
        type: "boolean",
        required: true,
        visible: true,
        order: 1,
      },
      {
        id: "zeit-ort.datum",
        section: "zeit-ort",
        title: "Datum des Vorfalls",
        type: "date",
        required: false,
        visible: true,
        order: 2,
        dependsOn: [{ questionId: "zeit-ort.datumBekannt", operator: "isTrue" }],
        requiredWhen: [{ questionId: "zeit-ort.datumBekannt", operator: "isTrue" }],
      },
      {
        id: "zeit-ort.zeitraum",
        section: "zeit-ort",
        title: "Ungefährer Zeitraum",
        description: "Falls das genaue Datum unbekannt ist: beschreiben Sie den Zeitraum oder wählen Sie „unbekannt“.",
        type: "text",
        required: false,
        visible: true,
        order: 3,
        dependsOn: [{ questionId: "zeit-ort.datumBekannt", operator: "isFalse" }],
        requiredWhen: [{ questionId: "zeit-ort.datumBekannt", operator: "isFalse" }],
      },
      {
        id: "zeit-ort.uhrzeit",
        section: "zeit-ort",
        title: "Uhrzeit",
        description: "Falls bekannt.",
        type: "time",
        required: false,
        visible: true,
        order: 4,
      },
      {
        id: "zeit-ort.ortstyp",
        section: "zeit-ort",
        title: "Art des Ortes",
        type: "singleChoice",
        required: true,
        visible: true,
        order: 5,
        options: [
          { value: "classroom", label: "Klassenraum" },
          { value: "schoolyard", label: "Schulhof" },
          { value: "hallway", label: "Flur oder Treppenhaus" },
          { value: "gym", label: "Sporthalle" },
          { value: "schoolTrip", label: "Schulveranstaltung außerhalb" },
          { value: "online", label: "Digitaler Raum" },
          { value: "outsideSchool", label: "Außerhalb der Schule" },
          { value: "unknown", label: "Unbekannt" },
        ],
      },
      {
        id: "zeit-ort.ort",
        section: "zeit-ort",
        title: "Genauere Ortsangabe",
        type: "location",
        required: false,
        visible: true,
        order: 6,
      },
      {
        id: "beteiligte.liste",
        section: "beteiligte",
        title: "Beteiligte Personen erfassen",
        description: "Erfassen Sie die beteiligten Personen ohne unnötige personenbezogene Details.",
        type: "participants",
        required: true,
        visible: true,
        order: 1,
      },
      {
        id: "betroffene.vorhanden",
        section: "betroffene",
        title: "Gibt es unmittelbar betroffene Personen?",
        type: "boolean",
        required: true,
        visible: true,
        order: 1,
      },
      {
        id: "betroffene.beschreibung",
        section: "betroffene",
        title: "Wer ist betroffen?",
        description: "Kennzeichnen Sie betroffene Personen zusätzlich in der Beteiligtenliste.",
        type: "textarea",
        required: false,
        visible: true,
        order: 2,
        dependsOn: [{ questionId: "betroffene.vorhanden", operator: "isTrue" }],
        requiredWhen: [{ questionId: "betroffene.vorhanden", operator: "isTrue" }],
      },
      {
        id: "zeugen.vorhanden",
        section: "zeugen",
        title: "Gab es Zeugen?",
        type: "boolean",
        required: true,
        visible: true,
        order: 1,
      },
      {
        id: "zeugen.liste",
        section: "zeugen",
        title: "Zeugen erfassen",
        type: "participant",
        required: false,
        visible: true,
        order: 2,
        dependsOn: [{ questionId: "zeugen.vorhanden", operator: "isTrue" }],
        requiredWhen: [{ questionId: "zeugen.vorhanden", operator: "isTrue" }],
        metadata: { editor: "witnesses" },
      },
      {
        id: "fortdauer.andauernd",
        section: "fortdauer",
        title: "Dauert die Situation aktuell an?",
        type: "boolean",
        required: true,
        visible: true,
        order: 1,
      },
      {
        id: "fortdauer.wiederholt",
        section: "fortdauer",
        title: "Hat sich die Situation wiederholt?",
        type: "boolean",
        required: true,
        visible: true,
        order: 2,
      },
      {
        id: "fortdauer.haeufigkeit",
        section: "fortdauer",
        title: "Wie oft und über welchen Zeitraum?",
        type: "text",
        required: false,
        visible: true,
        order: 3,
        dependsOn: [{ questionId: "fortdauer.wiederholt", operator: "isTrue" }],
        requiredWhen: [{ questionId: "fortdauer.wiederholt", operator: "isTrue" }],
      },
      {
        id: "gefahren.gemeldet",
        section: "gefahren",
        title: "Wurde eine akute Gefahr geschildert?",
        description: "Reine Angabe. Es erfolgt keine Bewertung durch das System.",
        type: "boolean",
        required: true,
        visible: true,
        order: 1,
      },
      {
        id: "gefahren.art",
        section: "gefahren",
        title: "Welche Gefahr wurde geschildert?",
        type: "text",
        required: false,
        visible: true,
        order: 2,
        dependsOn: [{ questionId: "gefahren.gemeldet", operator: "isTrue" }],
        requiredWhen: [{ questionId: "gefahren.gemeldet", operator: "isTrue" }],
      },
      {
        id: "gefahren.andauernd",
        section: "gefahren",
        title: "Besteht die geschilderte Gefahr weiterhin?",
        type: "boolean",
        required: false,
        visible: true,
        order: 3,
        dependsOn: [{ questionId: "gefahren.gemeldet", operator: "isTrue" }],
      },
      {
        id: "gefahren.rettungsdienste",
        section: "gefahren",
        title: "Waren Polizei, Rettungsdienst oder Feuerwehr eingebunden?",
        type: "boolean",
        required: false,
        visible: true,
        order: 4,
        dependsOn: [{ questionId: "gefahren.gemeldet", operator: "isTrue" }],
      },
      {
        id: "nachweise.vorhanden",
        section: "nachweise",
        title: "Liegen Nachweise oder Unterlagen vor?",
        type: "boolean",
        required: true,
        visible: true,
        order: 1,
      },
      {
        id: "nachweise.liste",
        section: "nachweise",
        title: "Nachweise erfassen",
        description: "Nur Angaben zur Art und Aufbewahrung. Keine Dateien hochladen.",
        type: "evidence",
        required: false,
        visible: true,
        order: 2,
        dependsOn: [{ questionId: "nachweise.vorhanden", operator: "isTrue" }],
        requiredWhen: [{ questionId: "nachweise.vorhanden", operator: "isTrue" }],
      },
      {
        id: "massnahmen.durchgefuehrt",
        section: "massnahmen",
        title: "Wurden bereits Maßnahmen durchgeführt?",
        type: "boolean",
        required: true,
        visible: true,
        order: 1,
      },
      {
        id: "massnahmen.liste",
        section: "massnahmen",
        title: "Maßnahmen erfassen",
        type: "measures",
        required: false,
        visible: true,
        order: 2,
        dependsOn: [{ questionId: "massnahmen.durchgefuehrt", operator: "isTrue" }],
        requiredWhen: [{ questionId: "massnahmen.durchgefuehrt", operator: "isTrue" }],
      },
      {
        id: "informierte.stellen",
        section: "informierte",
        title: "Wer wurde bereits informiert?",
        type: "multiChoice",
        required: true,
        visible: true,
        order: 1,
        options: [
          { value: "schoolLeadership", label: "Schulleitung" },
          { value: "classTeacher", label: "Klassenleitung" },
          { value: "parents", label: "Eltern oder Erziehungsberechtigte" },
          { value: "socialWork", label: "Schulsozialarbeit" },
          { value: "authority", label: "Schulaufsicht" },
          { value: "police", label: "Polizei" },
          { value: "none", label: "Bisher niemand" },
        ],
      },
      {
        id: "dokumentation.notizen",
        section: "dokumentation",
        title: "Liegen eigene Notizen vor?",
        type: "boolean",
        required: true,
        visible: true,
        order: 1,
      },
      {
        id: "dokumentation.vorfallsbericht",
        section: "dokumentation",
        title: "Existiert bereits ein Vorfallsbericht?",
        type: "boolean",
        required: true,
        visible: true,
        order: 2,
      },
      {
        id: "dokumentation.gespraechsnotiz",
        section: "dokumentation",
        title: "Existiert eine Gesprächsnotiz?",
        type: "boolean",
        required: false,
        visible: true,
        order: 3,
      },
      {
        id: "dokumentation.elternkontakt",
        section: "dokumentation",
        title: "Ist der Elternkontakt dokumentiert?",
        type: "boolean",
        required: false,
        visible: true,
        order: 4,
      },
      {
        id: "dokumentation.sonstiges",
        section: "dokumentation",
        title: "Weitere vorhandene Dokumentation",
        type: "textarea",
        required: false,
        visible: true,
        order: 5,
      },
      {
        id: "offene-fragen.hinweis",
        section: "offene-fragen",
        title: "Hinweis",
        description:
          "Angaben, die Sie nicht kennen, markieren Sie ausdrücklich als „unbekannt“. So bleibt nachvollziehbar, was offen ist.",
        type: "information",
        required: false,
        visible: true,
        order: 1,
      },
      {
        id: "offene-fragen.text",
        section: "offene-fragen",
        title: "Welche Fragen sind aus Ihrer Sicht offen?",
        type: "textarea",
        required: false,
        visible: true,
        order: 2,
      },
    ],
  };
}
